sudo: required

services:
  - docker

before_install:
  - docker build -t shadrach19/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shadrach19/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  app: "docker-react"
  env: "Docker-env"
  region: "us-east-1"
  bucket_name: "elasticbeanstalk-us-east-1-751808579985"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
